# Generated by Django 5.0.3 on 2024-03-20 00:41

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegenuine',
            name='Image',
            field=models.ImageField(upload_to=pages.models.generate_unique_filename),
        ),
    ]
