# Generated by Django 5.0.3 on 2024-03-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_medication_image_medication_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='image',
        ),
    ]
