# Generated by Django 5.0.3 on 2024-03-29 22:22

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=pages.models.generate_unique_filename),
        ),
    ]
